.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. lkcoinse_qt test_lkcoinse_qt
clean: FORCE
	$(MAKE) -C .. lkcoinse_qt_clean test_lkcoinse_qt_clean
check: FORCE
	$(MAKE) -C .. test_lkcoinse_qt_check
lkcoinse-qt lkcoinse-qt.exe: FORCE
	 $(MAKE) -C .. lkcoinse_qt
